language: objective-c
osx_image: xcode7.3
script:
  - make swift-install
  - . set-swift-env
  - $(env | grep -w PATH) =~ /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:*
  - $(env | grep -w TOOLCHAINS) = swift
